services:
  - type: web
    name: croor-game-support
    env: python
    buildCommand: pip install flask flask-cors requests gunicorn
    startCommand: cd /opt/render/project/src && gunicorn server:app --bind 0.0.0.0:$PORT
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
